"""Atualizando linhas da tabela StockMovement

Revision ID: 01fbc011bb2f
Revises: c12248d4a9c8
Create Date: 2026-07-26 17:16:37.600861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fbc011bb2f'
down_revision: Union[str, Sequence[str], None] = 'c12248d4a9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('stock_movements', sa.Column('stock_before', sa.Integer(), nullable=False))
    op.add_column('stock_movements', sa.Column('stock_after', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'stock_after')
    op.drop_column('stock_movements', 'stock_before')
    op.drop_column('stock_movements', 'quantity')
    # ### end Alembic commands ###
